name: Pull request

on:
  pull_request:
    branches:
      - release-1.4

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/test.yml
