name: Pull request

on:
  pull_request:
    branches:
      - release-2.2

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/test.yml

  pull-request:
    needs: build
    name: Pull request success
    runs-on: ubuntu-latest
    steps:
      - run: true
