name: Scheduled build

on:
  schedule:
    - cron: "5 0 * * *"
  pull_request:
    branches:
      - main

jobs:
  main:
    uses: ./.github/workflows/test.yml
  release-2_2:
    name: release-2.2
    uses: ${{ github.repository }}/.github/workflows/test.yml@release-2.2
    with:
      checkout-ref: release-2.2
