name: Scheduled build

on:
  schedule:
    - cron: "5 0 * * *"

env:
  FABRIC_VERSION: "2.2"
  GOPATH: ${{ github.workspace }}/src/test/fixture

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        java-version:
          - "8"
          - "11"
          - "17"
        ref:
          - main
          - release-2.2
    steps:
      - uses: actions/checkout@v3
        ref: ${{ matrix.ref }}
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin
          cache: maven
      - name: Integration tests
        run: ./scripts/run-integration-tests.sh
